server:
  port: 8082

spring:
  application:
    name: autor-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_autores}
    username: ${SPRING_DATASOURCE_USERNAME:biblioteca}
    password: ${SPRING_DATASOURCE_PASSWORD:biblioteca}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
