worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream front_ms { server front-ms:8080; }
    upstream livro_ms { server livro-ms:8081; }
    upstream autor_ms { server autor-ms:8082; }

    server {
        listen 80;
        server_name localhost;

        add_header Access-Control-Allow-Origin  "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/livros {
            if ($request_method = OPTIONS) { return 204; }
            proxy_pass http://livro_ms;
        }

        location /api/autores {
            if ($request_method = OPTIONS) { return 204; }
            proxy_pass http://autor_ms;
        }

        location /api/ {
            return 404;
        }

        location / {
            proxy_pass http://front_ms;
        }
    }
}
