server:
  port: 8080

spring:
  application:
    name: front-ms
  thymeleaf:
    cache: false

autores:
  api:
    url: ${AUTORES_API_URL:http://localhost:8082}
livros:
  api:
    url: ${LIVROS_API_URL:http://localhost:8081}
